### ISSUE TITLE
Drop support for Puppet v3

### ISSUE THREAD

**Issue by ghoneycutt** [ghoneycutt/puppet-module-yum#23]
Use branch `v2` - https://github.com/ghoneycutt/puppet-module-yum/tree/v2

PR is #25

- [x] data types
- [x] puppet string
- [x] data in module (not going to do this for this module)
- [x] fix fact warnings
- [x] vagrant
- [x] yum.conf is feature complete (for options that don't normally exist, make them `undef` by default and only added if a value has been specified)
- [x] define for repo.conf is feature complete
- [x] remove lsb* facts
- [x] use https://github.com/thrnio/puppet-ip to validate IP addresses
- [x] not dependent on ghoneycutt/common
  - [x] copy common::remove_if_empty and use that in rpm_gpg_key
  - [x] common::mkdir_p is not required
- [x] remove dependency on thrnio/ip as it is in stdlib >= 4.25.0
- [x] use puppetlabs/concat v4
- [x] use puppetlabs/apache v3
- [x] support only puppet 5
- [x] fix warnings below
- [x] README is properly formatted
- [x] use REFERENCE.md
- [x] basic acceptance tests with beaker

```
WARN  [qtp1341941325-65] [puppetserver] Puppet Unknown variable: '::lsbmajdistrelease'. at yum/manifests/repo.pp:127:98
WARN  [qtp1341941325-65] [puppetserver] Puppet Unknown variable: '::lsbminordistrelease'. at yum/manifests/repo.pp:127:121
WARN  [qtp1341941325-65] [puppetserver] Puppet Unknown variable: '::lsbmajdistrelease'. at yum/manifests/repo.pp:139:127
```

**Comment by ghoneycutt** [comment]
https://linux.die.net/man/5/yum.conf

**Comment by Phil-Friderici** [comment]
@ghoneycutt please check PR https://github.com/ghoneycutt/puppet-module-yum/pull/24.

Think that 'data in module' doesn't makes sense for this module.

**Comment by Phil-Friderici** [comment]
Unsure what is meant with the last three tasks: vagrant, yum.conf & repo.conf.

**Comment by ghoneycutt** [comment]
There should be a vagrant config that shows this works on EL5, 6 and 7 and that the server component works (EL7 only is fine).

yum.conf is feature complete, so all the available options in the man page can be configured through the module. Same with repo.conf to define all available options in a .repo file.

**Comment by ghoneycutt** [comment]
@Phil-Friderici how goes it?

**Comment by Phil-Friderici** [comment]
I am stuck on the vagrant details. Having problem to call/include the yum module itself. Vagrant always complains that it can't find the yum module. Guess the problem is that the /vagrant directory in the VM is not a valid module directory. Creating a copy inside a vagrant specifc folder to make it available looks so wrong to me.

Do you have any example module that I could learn from ? So far I only have found examples that use (external) Puppet modules to configure the VM.

**Comment by ghoneycutt** [comment]
@Phil-Friderici Check out 

https://github.com/sensu/sensu-puppet/blob/master/Vagrantfile#L109-L110

and

https://github.com/sensu/sensu-puppet/blob/master/tests/provision_basic_el.sh

**Comment by ghoneycutt** [comment]
Love all the activity in the PR! Let me know when it is feature complete and ready for review. Thanks @Phil-Friderici

**Comment by Phil-Friderici** [comment]
Will change the subject from (WIP) to (RTM) and send you a notice when ready to merge/review.

**Comment by Phil-Friderici** [comment]
Will change the subject from (WIP) to (RTM) and send you a notice when ready to merge/review.
This time I won, see the Travis results here: https://travis-ci.org/Phil-Friderici/puppet-module-yum/builds/315443621

**Comment by Phil-Friderici** [comment]
From my perspective yum.conf is feature complete now. Will continue with repo.conf.

**Comment by Phil-Friderici** [comment]
Seems we have a race condition for Travis runs between your repository and my. If it runs on your repo it will not run on my and vise versa.

**Comment by Phil-Friderici** [comment]
checked/ticked the accomplish tasks in the list.
