### ISSUE TITLE
yum::repo::gpgkey_url_server

### ISSUE THREAD

**Issue by Phil-Friderici** [ghoneycutt/puppet-module-yum#6]
In define yum::repo the parameter `$gpgkey_url_server` defaults to the parameter `$repo_server` [1]
This construct is not compatible with Puppet 4.0 to 4.3.

A workaround could be to set the default of $gpgkey_url_server to undef and assign it to $repo_server in the code.

<pre>
define yum::repo (
  $repo_server          = "yum.${::domain}",
  $gpgkey_url_server    = undef,
) {

if $gpgkey_url_server == undef {
  $gpgkey_url_server_real = $repo_server
}
</pre>

[1] https://github.com/ghoneycutt/puppet-module-yum/blob/master/manifests/repo.pp#L20-L26

**Comment by ghoneycutt** [comment]
suggest just duplicating the data instead of the conditional.

```puppet
define yum::repo (
  $repo_server       = "yum.${::domain}",
  $gpgkey_url_server = "yum.${::domain}",
) {
```

**Comment by Phil-Friderici** [comment]
well, that would be too easy ;)

**Comment by Phil-Friderici** [comment]
If someone only set `$repo_server` and expect the module to use the same value for `$gpg_url_server` the easy way wouldn't deliver the expected result. Think I will go for the first way.

**Comment by Phil-Friderici** [comment]
fixed in https://github.com/ghoneycutt/puppet-module-yum/commit/f7aa75bcf60b68282eba32559571683c78fbfb4d
